"""remove category and original_topic from articles

Revision ID: 518df3a10cd5
Revises: 58068f869124
Create Date: 2025-12-19 20:22:50.175559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518df3a10cd5'
down_revision: Union[str, Sequence[str], None] = '58068f869124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'original_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('original_topic', sa.TEXT(), autoincrement=False, nullable=True, comment='原始话题/素材'))
    op.add_column('articles', sa.Column('category', postgresql.ENUM('POLITICS', 'ECONOMY', 'SOCIETY', 'TECH', 'SPORTS', 'ENTERTAINMENT', 'INTERNATIONAL', 'MILITARY', 'CULTURE', 'LIFE', 'EDUCATION', 'HEALTH', 'DIGITAL', 'HOT', 'OTHER', name='articlecategory'), autoincrement=False, nullable=True, comment='分类'))
    # ### end Alembic commands ###
