"""add workflow tables

Revision ID: 58068f869124
Revises: 
Create Date: 2025-12-19 14:26:30.266470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58068f869124'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_sessions',
    sa.Column('article_id', sa.UUID(), nullable=False, comment='关联文章ID'),
    sa.Column('mode', sa.Enum('AUTO', 'MANUAL', name='workflowmode'), nullable=False, comment='工作流模式: auto-全自动, manual-半自动'),
    sa.Column('current_stage', sa.Enum('GENERATE', 'OPTIMIZE', 'IMAGE', 'EDIT', 'COMPLETED', name='workflowstage'), nullable=False, comment='当前阶段'),
    sa.Column('stage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='各阶段数据快照'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('progress', sa.String(length=10), nullable=True, comment='进度百分比'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='关联的工作流会话ID'),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='所属阶段: generate/optimize/image'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元数据: token_usage, prompt_id, model等'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workflow_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_stage'), 'conversation_messages', ['stage'], unique=False)
    op.alter_column('ai_configs', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='配置类型',
               existing_nullable=False)
    op.alter_column('ai_configs', 'api_key',
               existing_type=sa.TEXT(),
               comment='API Key',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_configs', 'api_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API URL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_configs', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment='模型名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_configs', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_configs', 'api_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='API URL',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_configs', 'api_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='API Key',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_configs', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='配置类型',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_messages_stage'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_table('workflow_sessions')
    # ### end Alembic commands ###
