"""add workflow_configs table

Revision ID: 5ebf51b6ca35
Revises: add_content_type_001
Create Date: 2025-12-23 16:18:18.997499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebf51b6ca35'
down_revision: Union[str, Sequence[str], None] = 'add_content_type_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 使用已存在的 contenttype 枚举类型
    contenttype_enum = postgresql.ENUM('ARTICLE', 'WEITOUTIAO', name='contenttype', create_type=False)

    op.create_table('workflow_configs',
    sa.Column('content_type', contenttype_enum, nullable=False, comment='内容类型: article-文章, weitoutiao-微头条'),
    sa.Column('enable_custom_topic', sa.Boolean(), nullable=False, comment='是否启用自定义话题'),
    sa.Column('enable_optimize', sa.Boolean(), nullable=False, comment='是否启用内容优化（去AI化）'),
    sa.Column('enable_image_gen', sa.Boolean(), nullable=False, comment='是否启用AI生图'),
    sa.Column('enable_auto_publish', sa.Boolean(), nullable=False, comment='是否启用自动发布'),
    sa.Column('custom_topic', sa.String(length=500), nullable=False, comment='自定义话题内容（当 enable_custom_topic=True 时使用）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_configs_content_type'), 'workflow_configs', ['content_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_configs_content_type'), table_name='workflow_configs')
    op.drop_table('workflow_configs')
    # ### end Alembic commands ###
