"""add tags field to articles

Revision ID: 9a97fb68e6f6
Revises: 2196edb9ac43
Create Date: 2025-12-24 15:24:42.845311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a97fb68e6f6'
down_revision: Union[str, Sequence[str], None] = '2196edb9ac43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='文章标签列表', server_default='[]'))
    op.alter_column('articles', 'content_type',
               existing_type=postgresql.ENUM('ARTICLE', 'WEITOUTIAO', name='contenttype'),
               comment='内容类型: article-文章, weitoutiao-微头条',
               existing_nullable=False,
               existing_server_default=sa.text("'ARTICLE'::contenttype"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'content_type',
               existing_type=postgresql.ENUM('ARTICLE', 'WEITOUTIAO', name='contenttype'),
               comment=None,
               existing_comment='内容类型: article-文章, weitoutiao-微头条',
               existing_nullable=False,
               existing_server_default=sa.text("'ARTICLE'::contenttype"))
    op.drop_column('articles', 'tags')
    # ### end Alembic commands ###
